options:
  vlan-ranges:
    type: string
    default: "physnet1:1000:2000"
    description: |
      Space-delimited list of Neutron network-provider & vlan-id-ranges using
      the following format "<provider>:<start>:<end> ...".
  overlay-network-type:
    default: gre
    type: string
    description: |
      Overlay network types to use, valid options include:
      .
        gre
        vxlan
      .
      Multiple types can be provided - field is space delimited.
  security-groups:
    default: false
    type: boolean
    description: Enable OpenDayLight managed security groups.
